/*
Navicat MySQL Data Transfer

Source Server         : local_root
Source Server Version : 50624
Source Host           : localhost:3306
Source Database       : scmsdb

Target Server Type    : MYSQL
Target Server Version : 50624
File Encoding         : 65001

Date: 2018-03-05 17:47:40
*/

SET FOREIGN_KEY_CHECKS=0;


-- ----------------------------
-- Table structure for `ACCOUNT_TYPE`
-- ----------------------------
DROP TABLE IF EXISTS `ACCOUNT_TYPE`;
CREATE TABLE `ACCOUNT_TYPE` (
  `ACCOUNT_TYPE_ID` int(11) NOT NULL AUTO_INCREMENT,
  `ACCOUNT_TYPE_CODE` varchar(20) NOT NULL,
  `ACCOUNT_TYPE_NAME` varchar(100) NOT NULL,
  PRIMARY KEY (`ACCOUNT_TYPE_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=46 DEFAULT CHARSET=utf8 COMMENT='ACCOUNT_TYPE';

-- ----------------------------
-- Records of ACCOUNT_TYPE
-- ----------------------------
INSERT INTO `ACCOUNT_TYPE` VALUES ('6', '1001', '天猫');
INSERT INTO `ACCOUNT_TYPE` VALUES ('7', '1002', 'QQ');
INSERT INTO `ACCOUNT_TYPE` VALUES ('8', '1003', '淘宝');
INSERT INTO `ACCOUNT_TYPE` VALUES ('9', '1004', 'Google');
INSERT INTO `ACCOUNT_TYPE` VALUES ('10', '1005', '百度');
INSERT INTO `ACCOUNT_TYPE` VALUES ('11', '1006', 'CSDN');
INSERT INTO `ACCOUNT_TYPE` VALUES ('12', '1007', '雅虎');
INSERT INTO `ACCOUNT_TYPE` VALUES ('13', '1008', '微软');
INSERT INTO `ACCOUNT_TYPE` VALUES ('14', '1009', '魅族');
INSERT INTO `ACCOUNT_TYPE` VALUES ('15', '1010', '小米');
INSERT INTO `ACCOUNT_TYPE` VALUES ('16', '1011', '华为');
INSERT INTO `ACCOUNT_TYPE` VALUES ('17', '1012', '锤子');
INSERT INTO `ACCOUNT_TYPE` VALUES ('18', '1013', '乐视');
INSERT INTO `ACCOUNT_TYPE` VALUES ('19', '1014', '一加');
INSERT INTO `ACCOUNT_TYPE` VALUES ('20', '1015', '酷派');
INSERT INTO `ACCOUNT_TYPE` VALUES ('21', '1016', '360');
INSERT INTO `ACCOUNT_TYPE` VALUES ('22', '1017', '中兴');
INSERT INTO `ACCOUNT_TYPE` VALUES ('23', '1018', '阿里巴巴');
INSERT INTO `ACCOUNT_TYPE` VALUES ('24', '1019', '京东');
INSERT INTO `ACCOUNT_TYPE` VALUES ('25', '1020', '苏宁');
INSERT INTO `ACCOUNT_TYPE` VALUES ('26', '1021', '国美');
INSERT INTO `ACCOUNT_TYPE` VALUES ('27', '1022', '亚马逊');
INSERT INTO `ACCOUNT_TYPE` VALUES ('28', '1023', '当当网');
INSERT INTO `ACCOUNT_TYPE` VALUES ('29', '1024', '华硕');
INSERT INTO `ACCOUNT_TYPE` VALUES ('30', '1025', '小天鹅');
INSERT INTO `ACCOUNT_TYPE` VALUES ('31', '1026', '花生壳');
INSERT INTO `ACCOUNT_TYPE` VALUES ('32', '1027', '迅雷');
INSERT INTO `ACCOUNT_TYPE` VALUES ('33', '1028', '微博');
INSERT INTO `ACCOUNT_TYPE` VALUES ('34', '1029', 'gitHub');
INSERT INTO `ACCOUNT_TYPE` VALUES ('35', '1030', 'Facebook');
INSERT INTO `ACCOUNT_TYPE` VALUES ('36', '1030', 'Facebook');
INSERT INTO `ACCOUNT_TYPE` VALUES ('37', '1031', 'Email');
INSERT INTO `ACCOUNT_TYPE` VALUES ('38', '1032', '其他');
INSERT INTO `ACCOUNT_TYPE` VALUES ('39', '1033', '支付宝');
INSERT INTO `ACCOUNT_TYPE` VALUES ('40', '1034', '12306');
INSERT INTO `ACCOUNT_TYPE` VALUES ('41', '1035', '搬瓦工vps');
INSERT INTO `ACCOUNT_TYPE` VALUES ('42', '1036', 'cnblog');
INSERT INTO `ACCOUNT_TYPE` VALUES ('43', '1037', '拉钩网');
INSERT INTO `ACCOUNT_TYPE` VALUES ('44', '1038', 'paypal');
INSERT INTO `ACCOUNT_TYPE` VALUES ('45', '1039', '自定义12');
INSERT INTO `ACCOUNT_TYPE` VALUES ('46', '1040', 'viishow_cn');



DROP TABLE IF EXISTS `ACCOUNT`;
CREATE TABLE `ACCOUNT` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `TYPE_ID` int(11) DEFAULT NULL,
  `ACCOUNT_STR` varchar(1024) NOT NULL,
  `PASSWD_STR` varchar(1024) NOT NULL,
  `NOTE` varchar(1024) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_Reference_6` (`TYPE_ID`),
  CONSTRAINT `FK_Reference_6` FOREIGN KEY (`TYPE_ID`) REFERENCES `ACCOUNT_TYPE` (`ACCOUNT_TYPE_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8 COMMENT='ACCOUNT';


-- ----------------------------
-- Records of ACCOUNT
-- ----------------------------
INSERT INTO `ACCOUNT` VALUES ('1', '46', '3232', '323', '2323');
INSERT INTO `ACCOUNT` VALUES ('2', '45', '22', '22', '22');
INSERT INTO `ACCOUNT` VALUES ('3', '11', '1', '1', '1');
INSERT INTO `ACCOUNT` VALUES ('4', '46', 'fwe', 'fwe', 'few');
INSERT INTO `ACCOUNT` VALUES ('5', '46', '323', '32', '32');
INSERT INTO `ACCOUNT` VALUES ('6', '44', '5435', '4534', '54353');


DROP TABLE IF EXISTS `ATTACHMENT`;
CREATE TABLE `ATTACHMENT` (
	`FILE_ID` varchar(32) NOT NULL,
	`FILE_NAME` varchar(1024) NULL,
	`FILE_GROUP` varchar(1024) NULL,
	`ORGN_NAME` varchar(1024) NULL,
	`FILE_SIZE` varchar(1024) NULL,
	`FILE_EXT` varchar(1024) NULL,
	`FILE_PATH` varchar(1024) NULL,
	PRIMARY KEY (`FILE_ID`) 

) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='ATTACHMENT';



